# docker-compose.override.yml
version: '3.8'

services:
  backend:
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True

  celery_worker:
    environment:
      - DEBUG=True

  celery_beat:
    environment:
      - DEBUG=True

  flower:
    environment:
      - DEBUG=True