# Generated by Django 5.2.8 on 2025-12-04 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Course title', max_length=255, verbose_name='title')),
                ('preview', models.ImageField(blank=True, help_text='Course preview image', null=True, upload_to='courses/previews/', verbose_name='preview image')),
                ('description', models.TextField(blank=True, help_text='Course description', null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Lesson title', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Lesson description', null=True, verbose_name='description')),
                ('preview', models.ImageField(blank=True, help_text='Lesson preview image', null=True, upload_to='lessons/previews/', verbose_name='preview image')),
                ('video_url', models.URLField(help_text='URL to the lesson video', max_length=500, verbose_name='video URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('course', models.ForeignKey(help_text='Related course', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='materials.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ['created_at'],
            },
        ),
    ]
